checks:
  javascript: true
filter:
  excluded_paths:
    - node_modules/*

build:
  environment:
    node: 7

  dependencies:
    before:
      - npm install grunt-cli -g
      - npm install

  tests:
    override:
      -
        command: 'grunt'
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'clover'
